### ISSUE TITLE
VO 학습

### ISSUE THREAD

**Issue by kyupid** [kyupid/java-chess-again#10]
읽은것: https://livenow14.tistory.com/18

글 작성중

**Comment by ghojeong** [comment]
Value Object 라는 말이 나와서, 문득 궁금해졌는데,

코틀린에서 [Data Class](https://kotlinlang.org/docs/data-classes.html) 랑,
[Value Class](https://kotlinlang.org/docs/inline-classes.html) 가 헷갈려서 질문드립니다.

둘다 Value Object 라고 볼 수 있는 것인가요?
아니면 둘중 하나만 Value Object 라고 보아야 하나요?

그리고 Value Object 에 로직이 허용될 수 있는지, (예를 들어서 validation 로직),
아니면 철저하게 모든 로직이 배제되어야 하는지도 질문드립니다.

DTO 에는 로직이 허용될 수 있다고 알고 있는데,
Value Object 에는 로직을 허용해서는 안된다는 의견을 가지신 분도 있다고 들어서요.

@tmdgusya

**Comment by kyupid** [comment]
https://kyucumber.tistory.com/3
완료

**Comment by tmdgusya** [comment]
> 

음 일단 Kotlin 의 Data Class 의 경우 값객체로 쓰이는 것들이 인스턴스가 계속해서 생성되는 것이 
부담되어서 만들어진 새로운 개념으로 알고있고요. 
둘의 차이는 ComponentN() 이 추가적으로 생기느냐 마느냐의 차이, 그리고 val, Mutable 차이가 있겠네요.
자세한 글은 아래 분이 설명을 잘 해주신거 같아서 읽어보시면 좋을거 같아요

https://velog.io/@dhwlddjgmanf/Kotlin-1.5%EC%97%90-%EC%B6%94%EA%B0%80%EB%90%9C-value-class%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

일단 제 생각에 Value Object 에 어떤 로직이 들어가느냐의 차이인거 같은데
제 견해상으로는 self-validation 은 들어가는게 맞지 않나 싶기도 하네요.

외부에서 이 값 객체가 어떤 식으로 validation 되어야 하는지 알아야 한다면,
이 value object 를 쓰는 곳 마다 validation 을 해줘야 하지않을까요? 응집도에 문제가 있을 수 있다고 생각합니다.

쉬운 예시를 들면 

```java
public class Account {
    private int money;
}

public class Account {
   private Money money;
}
```

위와 같이 사용하는 이유는 Account 에 있는 money 의 int (정수값의 범위) 가 현실세계의 "돈" 개념과 멀어지기 때문도 있지만,
Money 를 사용하는 곳에서 중복되는 Validation 이 일어날 수도 있기에
Money 에 Self-Validation (음수로 떨어지지 않는) 을 넣는것이라고 생각됩니다.

**Comment by ghojeong** [comment]
훌륭한 답변 감사합니다!
@tmdgusya
