### ISSUE TITLE
스프링 시큐리티 회원가입과 로그인 실습

### ISSUE THREAD

**Issue by kyupid** [kyupid/java-chess-again#34]
리포: https://github.com/kyupid/spring-security-signup-and-login
튜토리얼: https://shinsunyoung.tistory.com/78

- [x] 2021-12-29 튜토리얼 진행후 마이바티스 성공적으로 적용한다. (실습용 리포지토리는 오늘 무조건 끝내야함)
- [x] 2021-12-30 실제 프로젝트에 적용한다.
- [ ] 2021-12-31 발생한 예외사항 등 처리한다.

---

## 2022-01-01 업데이트
세션을 이용하라고 해서 구현하라해서 찾아봤으나
시간부족으로 다음과 같이 구현하기로 함
- [x] 2021-01-02 https://github.com/kyupid/java-chess-again/issues/44#issuecomment-1003524852
- [x] 2021-01-02 로그인, 임시비밀번호발급

일요일에는 무조건 마무리해야함.

---

## 2022-01-06 업데이트
- 예외처리 제대로 필요

**Comment by ghojeong** [comment]
우와 이건 저에게도 유용하네요.
감사합니다 Kyu!

**Comment by kyupid** [comment]
너무 친절하게도 코드 복붙만 하면 되도록 적혀있네요 ㅎㅎ
