### ISSUE TITLE
Optional 사용

### ISSUE THREAD

**Issue by kyupid** [kyupid/java-chess-again#58]
https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

**Comment by ghojeong** [comment]
주말에도 쉬지 않는군요 Kyu...
무시무시하네요

**Comment by kyupid** [comment]
@ghojeong ㅋㅋㅋ 조금 했어요 배울게 넘 많네요 ㅋㅋㅋ

**Comment by ghojeong** [comment]
Kyu 의 잔디밭도 저랑 비슷해지겠군요 ㅋㅋㅋ
